db:
  DIAL : "postgresql"
  DRV : "psycopg2"
  HOST : "rc1b-o3ezvcgz5072sgar.mdb.yandexcloud.net"
  PORT : "6432"
  BD : "db"
  LOGIN : "hse"
  PAS : "hsepassword"
files:
  path_to_input : "/opt/airflow/project/input"
  path_to_archive : "/opt/airflow/project/archive" 